# Generated by Django 2.0.2 on 2018-03-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0002_auto_20180327_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详细')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, '未处理'), (2, '处理中'), (3, '已处理')], default=1)),
                ('solution', models.TextField(blank=True, null=True)),
                ('ptime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete='', to='rbac.User')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='create_user',
            field=models.ForeignKey(on_delete='', related_name='aaa', to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete='', related_name='bbb', to='app01.UserInfo'),
        ),
    ]
